// Adversarial tests for the derived-inventory exemption in the currency gate.
//
// The exemption lets the GENERATED integrity inventory (sw.js's embedded manifest block, the JSON it
// is generated from, and the generator) hold runtime URL literals without them being read as
// unauthorised route pins. That is a deliberate hole in a security/currency gate, so these tests exist
// to prove the hole is the size we claim and no larger.
//
// A previous revision of this exemption was BLOCKED because it was file-scoped: a pin placed inside the
// generated block, or a hand-written pin in the generator's arrays, was silently exempted. Rather than
// record that finding once in a review comment, each case below re-instates the attack and asserts the
// gate still fails. If someone widens the exemption again, these tests fail.
//
// Each case mutates a real file, runs the gate, and restores byte-exactly in a finally block.

import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

/** Runs the currency gate. Returns its exit code rather than throwing style-dependent errors. */
function runGate() {
  try {
    execFileSync("node", ["scripts/audit-model-currency.mjs", "--check"], {
      cwd: ROOT,
      stdio: "pipe",
    });
    return 0;
  } catch (error) {
    return typeof error.status === "number" ? error.status : 1;
  }
}

/** Applies a text mutation to a real file, runs the assertion, then restores it byte-exactly. */
function withMutation(relativePath, mutate, assertion) {
  const path = join(ROOT, relativePath);
  const original = readFileSync(path, "utf8");
  try {
    writeFileSync(path, mutate(original));
    assertion();
  } finally {
    writeFileSync(path, original);
  }
  assert.equal(readFileSync(path, "utf8"), original, `${relativePath} must be restored byte-exactly`);
}

const insertBeforeClosingMarker = (source) => {
  const lines = source.split("\n");
  const index = lines.findIndex((line) => line.includes("<<< runtime-integrity"));
  assert.ok(index > 0, "sw.js must contain the closing runtime-integrity marker");
  lines.splice(index, 0, 'const smuggled = "https://cdn.jsdelivr.net/npm/onnxruntime-web@9.9.9/dist/ort.wasm.min.mjs";');
  return lines.join("\n");
};

const ORT_PIN = 'importScripts("https://cdn.jsdelivr.net/npm/onnxruntime-web@9.9.9/dist/ort.min.js");';

test("baseline: the gate passes with no mutation", () => {
  assert.equal(runGate(), 0, "the unmutated tree must pass; the cases below are only meaningful against a green baseline");
});

test("an unauthorised pin in sw.js OUTSIDE the generated block still fails", () => {
  withMutation(
    "sw.js",
    (source) => `${source}\n${ORT_PIN}\n`,
    () => assert.equal(runGate(), 1, "a pin appended after the generated block must not be exempt"),
  );
});

test("an unauthorised pin in sw.js INSIDE the generated block still fails", () => {
  // This is the case that defeated the previous file-scoped revision.
  withMutation("sw.js", insertBeforeClosingMarker, () =>
    assert.equal(runGate(), 1, "a pin smuggled into the generated block must not be exempt"),
  );
});

test("an unauthorised pin ON the closing marker line still fails", () => {
  withMutation(
    "sw.js",
    (source) =>
      source
        .split("\n")
        .map((line) => (line.includes("<<< runtime-integrity") ? `const m = "onnxruntime-web@9.9.9"; ${line}` : line))
        .join("\n"),
    () => assert.equal(runGate(), 1, "a pin riding on a marker line must not be exempt"),
  );
});

test("a duplicated generated marker fails loudly instead of widening the exemption", () => {
  withMutation(
    "sw.js",
    (source) => {
      const lines = source.split("\n");
      const index = lines.findIndex((line) => line.includes(">>> runtime-integrity (generated"));
      assert.ok(index > 0, "sw.js must contain the opening runtime-integrity marker");
      lines.splice(index, 0, "// >>> runtime-integrity (generated by scripts/runtime-integrity.mjs)");
      return lines.join("\n");
    },
    () => assert.equal(runGate(), 1, "duplicated markers must disable the exemption, not extend it"),
  );
});

test("an unauthorised pin in a MODEL ROUTE still fails", () => {
  withMutation(
    "models/animegan-cartoonization/worker.js",
    (source) => `${source}\n${ORT_PIN}\n`,
    () => assert.equal(runGate(), 1, "no model route may ever be exempt from the currency gate"),
  );
});

test("an unauthorised version in the GENERATOR's arrays still fails", () => {
  // scripts/runtime-integrity.mjs is NOT generated - it holds hand-written arrays - so exempting it
  // wholesale (as the first revision did) hid real pin decisions.
  withMutation(
    "scripts/runtime-integrity.mjs",
    (source) => source.replace("const ORT_ASSETS = [", 'const ORT_ASSETS = [\n  "onnxruntime-web@9.9.9/dist/ort.wasm.min.mjs",'),
    () => assert.equal(runGate(), 1, "the generator must not be a place to hide an unauthorised pin"),
  );
});

test("an unauthorised version written into runtime-integrity.json still fails", () => {
  withMutation(
    "runtime-integrity.json",
    (source) => {
      const data = JSON.parse(source);
      data.urls["https://cdn.jsdelivr.net/npm/onnxruntime-web@9.9.9/dist/ort.wasm.min.mjs"] = {
        sha256: "0".repeat(64),
        bytes: 1,
        policy: "verify-then-cache",
      };
      return `${JSON.stringify(data, null, 2)}\n`;
    },
    () => assert.equal(runGate(), 1, "the generated data file must not be a place to authorise a new pin"),
  );
});

test("adding an arbitrary file to derivedInventory.files is rejected", () => {
  withMutation(
    "scripts/runtime-pin-allowlist.json",
    (source) => {
      const data = JSON.parse(source);
      data.derivedInventory.files.push("models/animegan-cartoonization/worker.js");
      return `${JSON.stringify(data, null, 2)}\n`;
    },
    () => assert.equal(runGate(), 1, "the exempt file set must be a fixed allowlist, not data anyone can extend"),
  );
});

test("COORD'S EXACT BYPASS: adding a route file to derivedInventory.files AND injecting a pin into it", () => {
  // The precise mutation to close: exempt a route file via the data, then hide a forbidden pin inside it.
  // If the exempt set is only "currently exact", this succeeds and the audit PASSES. It must not.
  const routeRel = "models/example-route/index.html";
  const routeAbs = join(ROOT, routeRel);
  const allowPath = join(ROOT, "scripts/runtime-pin-allowlist.json");
  const allowOriginal = readFileSync(allowPath, "utf8");
  let createdDir = false;
  try {
    try {
      mkdirSync(join(ROOT, "models/example-route"), { recursive: true });
      createdDir = true;
    } catch {
      // directory may already exist
    }
    writeFileSync(routeAbs, `<script src="https://cdn.jsdelivr.net/npm/onnxruntime-web@9.9.9/dist/ort.min.js"></script>\n`);
    const data = JSON.parse(allowOriginal);
    data.derivedInventory.files.push(routeRel);
    writeFileSync(allowPath, `${JSON.stringify(data, null, 2)}\n`);
    assert.equal(runGate(), 1, "exempting a route file via derivedInventory.files must be rejected outright");
  } finally {
    writeFileSync(allowPath, allowOriginal);
    try {
      rmSync(routeAbs, { force: true });
      if (createdDir) rmSync(join(ROOT, "models/example-route"), { recursive: true, force: true });
    } catch {
      // best effort cleanup
    }
  }
  assert.equal(readFileSync(allowPath, "utf8"), allowOriginal, "allowlist must be restored byte-exactly");
  assert.equal(existsSync(routeAbs), false, "the temporary route file must be removed");
});

test("the exempt set cannot be silently narrowed either", () => {
  withMutation(
    "scripts/runtime-pin-allowlist.json",
    (source) => {
      const data = JSON.parse(source);
      data.derivedInventory.files = ["sw.js"];
      return `${JSON.stringify(data, null, 2)}\n`;
    },
    () => assert.equal(runGate(), 1, "the exempt set must equal the intended immutable list exactly"),
  );
});

test("an INVERTED marker pair fails loudly", () => {
  withMutation(
    "sw.js",
    (source) => {
      const lines = source.split("\n");
      const open = lines.findIndex((l) => l.includes(">>> runtime-integrity (generated"));
      const close = lines.findIndex((l) => l.includes("<<< runtime-integrity"));
      const tmp = lines[open];
      lines[open] = lines[close];
      lines[close] = tmp;
      return lines.join("\n");
    },
    () => assert.equal(runGate(), 1, "an inverted marker pair must disable the exemption and error"),
  );
});
