// Service worker — offline app shell + resilient serving of large model blobs.
// Adapted from image-embedding-lab's sw.js. Bump SW_VERSION on every deploy.
//
// CACHE OWNERSHIP (learned the hard way in image-embedding-lab):
// - Transformers.js keeps its OWN Cache Storage cache ('transformers-cache') and writes every model
//   file there — including loads the SW never sees (first visit before control, hard reloads). NEVER
//   delete or duplicate it. Serve model files via caches.match() across ALL caches; do not re-store
//   another copy. Double-storing ~GB models is what pushes an origin into quota eviction.
// - We only cache the small app shell (HTML/CSS/JS/JSON) ourselves.
const SW_VERSION = "2026-09-24-memory-manual-only";
const SHELL_CACHE = `webai-shell-${SW_VERSION}`;
const MODEL_HOSTS = ["huggingface.co", "cdn-lfs.huggingface.co", "cdn-lfs-us-1.huggingface.co"];
const LIB_HOSTS = ["cdn.jsdelivr.net"];

// >>> runtime-integrity (generated by scripts/runtime-integrity.mjs)
const RUNTIME_INTEGRITY = {
  "https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.7.5": {
    "sha256": "770f4cfc9857958f8db9c783b406b1c7f3beb3ce0c9b72776ca1e973dae9e145",
    "bytes": 873307
  },
  "https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.7.5/dist/ort-wasm-simd-threaded.jsep.wasm": {
    "sha256": "c46655e8a94afc45338d4cb2b840475f88e5012d524509916e505079c00bfa39",
    "bytes": 21596019
  },
  "https://cdn.jsdelivr.net/npm/@huggingface/transformers@4.2.0": {
    "sha256": "e74bd32ed4453369ebb0edcaa27f6bc6204004a949a0233cdb87b62dda8d6978",
    "bytes": 558373
  },
  "https://cdn.jsdelivr.net/npm/@huggingface/transformers@4.3.0": {
    "sha256": "1475fd440e9932ab206682ee42cb18f6097403e9ee77ea62084c592d0f83597d",
    "bytes": 581935
  }
};
// <<< runtime-integrity

// Third-party runtime integrity. lib/webai.js loads the runtime with a dynamic import(), which has no
// integrity option in browsers today, so the worker is the only place its bytes can be checked.
// Verification runs on EVERY serve - a cache hit as well as a network response - because checking only
// before storing cannot detect an entry poisoned after it was stored.
//
// What this does NOT cover, stated here so it is not mistaken for complete protection: a first
// uncontrolled dynamic import that happens before this worker is controlling, and any browser
// HTTP-cache poisoning, which happens below the worker entirely.
async function sha256Hex(bytes) {
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

// A response whose bytes do not match the pin is never served, from cache or network.
function integrityFailure() {
  return new Response("Runtime integrity check failed", {
    status: 502,
    headers: { "content-type": "text/plain; charset=utf-8" },
  });
}

async function verifiedLibraryResponse(req, expected) {
  const cached = await caches.match(req);
  if (cached) {
    if (await sha256Hex(await cached.clone().arrayBuffer()) === expected) return cached;
    // Poisoned after it was stored. Evict it so no later request can be served from it either, then
    // fall through to the network for a clean copy rather than serving the bad bytes.
    (await caches.open(SHELL_CACHE)).delete(req).catch(() => {});
  }
  let res;
  try {
    res = await fetch(req);
  } catch {
    // Offline with no verified copy available. Fail closed: an unverified runtime is not served.
    return integrityFailure();
  }
  if (!res.ok) return res;
  if (await sha256Hex(await res.clone().arrayBuffer()) !== expected) return integrityFailure();
  const copy = res.clone();
  caches.open(SHELL_CACHE).then((c) => c.put(req, copy)).catch(() => {});
  return res;
}

self.addEventListener("install", (e) => {
  self.skipWaiting();
  e.waitUntil(caches.open(SHELL_CACHE).catch(() => {}));
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          // Delete ONLY our own outdated shell caches. transformers-cache and any library cache are
          // load-bearing model storage — never touch them.
          keys.filter((k) => k.startsWith("webai-shell-") && k !== SHELL_CACHE).map((k) => caches.delete(k)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);

  // Model blobs (HF): cache-first across ALL caches, never double-store. transformers.js owns those
  // bytes in its own cache, and re-storing ~GB models is what pushes an origin into quota eviction.
  if (MODEL_HOSTS.includes(url.hostname)) {
    e.respondWith(caches.match(req).then((hit) => hit || fetch(req)));
    return;
  }

  // Third-party runtime JS/WASM (jsDelivr): served only when its bytes match the pinned hash, cache
  // hit or network. A runtime URL that is NOT in the manifest is unknown/unpinned: it is fetched but
  // never served from the shell cache and never stored as a trusted shell asset, so an unlisted
  // runtime cannot inherit trust it was never granted.
  if (LIB_HOSTS.includes(url.hostname)) {
    const expected = RUNTIME_INTEGRITY[req.url];
    if (!expected) {
      e.respondWith(fetch(req));
      return;
    }
    e.respondWith(verifiedLibraryResponse(req, expected));
    return;
  }

  // Same-origin app shell: cache-first with background revalidation (stale-while-revalidate).
  // Returning users get an instant load from cache — the model check starts immediately instead of
  // after the full HTML/CSS/JS network round-trip — while the network refreshes the cache in the
  // background so the next visit is current. (Previously network-first: every page load serialised
  // the shell round-trip before the demo's "Checking for a local copy…" could even begin, which is
  // what felt like waiting on a server response for an already-local model.)
  if (url.origin === self.location.origin) {
    e.respondWith(
      (async () => {
        const cached = await caches.match(req);
        const network = fetch(req)
          .then((res) => {
            if (res.ok) {
              const copy = res.clone();
              caches.open(SHELL_CACHE).then((c) => c.put(req, copy)).catch(() => {});
            }
            return res;
          })
          .catch(() => cached);
        return cached || network;
      })(),
    );
    return;
  }
});
