// Service worker — offline app shell + resilient serving of large model blobs.
// Adapted from image-embedding-lab's sw.js. Bump SW_VERSION on every deploy.
//
// CACHE OWNERSHIP (learned the hard way in image-embedding-lab):
// - Transformers.js keeps its OWN Cache Storage cache ('transformers-cache') and writes every model
//   file there — including loads the SW never sees (first visit before control, hard reloads). NEVER
//   delete or duplicate it. Serve model files via caches.match() across ALL caches; do not re-store
//   another copy. Double-storing ~GB models is what pushes an origin into quota eviction.
// - We only cache the small app shell (HTML/CSS/JS/JSON) ourselves.
const SW_VERSION = "2026-09-24-memory-manual-only";
const SHELL_CACHE = `webai-shell-${SW_VERSION}`;
const MODEL_HOSTS = ["huggingface.co", "cdn-lfs.huggingface.co", "cdn-lfs-us-1.huggingface.co"];
const LIB_HOSTS = ["cdn.jsdelivr.net"];

// >>> runtime-integrity (generated by scripts/runtime-integrity.mjs)
const RUNTIME_INTEGRITY = {
  "https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.1.2/+esm": {
    "sha256": "7f4df4c1da993cc938b924e09b689f676900efa00cee84ce4fc22e934e0d5598",
    "bytes": 835445,
    "policy": "verify-then-cache"
  },
  "https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.7.5": {
    "sha256": "770f4cfc9857958f8db9c783b406b1c7f3beb3ce0c9b72776ca1e973dae9e145",
    "bytes": 873307,
    "policy": "verify-then-cache"
  },
  "https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.7.5/dist/ort-wasm-simd-threaded.jsep.mjs": {
    "sha256": "08fb86ec433c78bfb032c5d84a68b8e8e5a8d81268fa39e24314179a5767a5b9",
    "bytes": 44484,
    "policy": "verify-then-cache"
  },
  "https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.7.5/dist/ort-wasm-simd-threaded.jsep.wasm": {
    "sha256": "c46655e8a94afc45338d4cb2b840475f88e5012d524509916e505079c00bfa39",
    "bytes": 21596019,
    "policy": "verify-then-cache"
  },
  "https://cdn.jsdelivr.net/npm/@huggingface/transformers@4.2.0": {
    "sha256": "e74bd32ed4453369ebb0edcaa27f6bc6204004a949a0233cdb87b62dda8d6978",
    "bytes": 558373,
    "policy": "verify-then-cache"
  },
  "https://cdn.jsdelivr.net/npm/@huggingface/transformers@4.3.0": {
    "sha256": "1475fd440e9932ab206682ee42cb18f6097403e9ee77ea62084c592d0f83597d",
    "bytes": 581935,
    "policy": "verify-then-cache"
  },
  "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.18": {
    "sha256": "e703794a5bf463579cf72ba56acc08f48d35d2b170120fcb8c20b95241ff1c6d",
    "bytes": 140244,
    "policy": "verify-then-cache"
  },
  "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.18/wasm/vision_wasm_internal.js": {
    "sha256": "2b120e1c7272905719f7893e5f09e033ead468b46b510e6b490d93e3d94ec69c",
    "bytes": 203819,
    "policy": "verify-then-cache"
  },
  "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.18/wasm/vision_wasm_internal.wasm": {
    "sha256": "35d67ac01df034a04a38cb0533d6438595bcc65c485aed61dd47c86c6c3839cd",
    "bytes": 9502124,
    "policy": "verify-then-cache"
  },
  "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.18/wasm/vision_wasm_nosimd_internal.js": {
    "sha256": "d206ba4e27c42a5863b4001c6d9366345f4507979cd6efd087a149ef7781ccd3",
    "bytes": 203672,
    "policy": "verify-then-cache"
  },
  "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.18/wasm/vision_wasm_nosimd_internal.wasm": {
    "sha256": "17c2bff095305fcae98faa0817cbf72f13df9baf76f2067992a8624ef54d18cb",
    "bytes": 9376240,
    "policy": "verify-then-cache"
  },
  "https://cdn.jsdelivr.net/npm/onnxruntime-web@1.20.1/dist/ort-wasm-simd-threaded.jsep.mjs": {
    "sha256": "2fb14505d39926e4c544de8c57fe59a2f2bc74caba6f71890be9afecc5046758",
    "bytes": 46839,
    "policy": "verify-then-cache"
  },
  "https://cdn.jsdelivr.net/npm/onnxruntime-web@1.20.1/dist/ort-wasm-simd-threaded.jsep.wasm": {
    "sha256": "185b0861a6cd6cbdfb057289338090436483cc59e10a7bc83bd167b15531a51b",
    "bytes": 21663894,
    "policy": "verify-then-cache"
  },
  "https://cdn.jsdelivr.net/npm/onnxruntime-web@1.20.1/dist/ort.wasm.min.mjs": {
    "sha256": "f53ed4792e758e7232f779d479eb8931b97ff3ab2e3b9a33ee00d1251ffdaad6",
    "bytes": 48904,
    "policy": "verify-then-cache"
  },
  "https://cdn.jsdelivr.net/npm/onnxruntime-web@1.20.1/dist/ort.webgpu.min.mjs": {
    "sha256": "e1a0817ac08d5a6ade7f229754c2aecd444bff0bd22c259ca148a04b9f9e9f65",
    "bytes": 333468,
    "policy": "verify-then-cache"
  },
  "https://cdn.jsdelivr.net/npm/onnxruntime-web@1.21.0/dist/ort-wasm-simd-threaded.mjs": {
    "sha256": "e9ba2350c370278fc90108f1514fb9ce6a4051341ab977b5b0dca7eca9e78dfa",
    "bytes": 26583,
    "policy": "verify-then-cache"
  },
  "https://cdn.jsdelivr.net/npm/onnxruntime-web@1.21.0/dist/ort-wasm-simd-threaded.wasm": {
    "sha256": "06b3f98e5aa2fffec1e3ac57a48bf1073828c6624e14d210750bc596c2e35d65",
    "bytes": 12666427,
    "policy": "verify-then-cache"
  },
  "https://cdn.jsdelivr.net/npm/onnxruntime-web@1.21.0/dist/ort.min.mjs": {
    "sha256": "f04e7c794f156c0e2b109497456c3abea148f4c8bd234230e94bc2f571716a92",
    "bytes": 347679,
    "policy": "verify-then-cache"
  },
  "https://cdn.jsdelivr.net/npm/onnxruntime-web@1.21.0/dist/ort.wasm.min.mjs": {
    "sha256": "5118f6b62b123b74a7af80dccd6dc96d3651a39d02b37edfc0d9831982f1f898",
    "bytes": 46517,
    "policy": "verify-then-cache"
  },
  "https://cdn.jsdelivr.net/npm/onnxruntime-web@1.22.0/dist/ort-wasm-simd-threaded.jsep.mjs": {
    "sha256": "1cbcba8f2c769c1eecbab66a1b1e55ef11704515bf4306373e3db3c37cf6dcd8",
    "bytes": 44677,
    "policy": "verify-then-cache"
  },
  "https://cdn.jsdelivr.net/npm/onnxruntime-web@1.22.0/dist/ort-wasm-simd-threaded.jsep.wasm": {
    "sha256": "b45970d0632383a057c27ca5b660b216f8e00c17cf8db9f6207b5e4abc839368",
    "bytes": 21872216,
    "policy": "verify-then-cache"
  },
  "https://cdn.jsdelivr.net/npm/onnxruntime-web@1.22.0/dist/ort.webgpu.min.mjs": {
    "sha256": "e131e81c9324807e1e6f9103e8f8e936112827dcc9993cde9407a333b1f07ae0",
    "bytes": 357582,
    "policy": "verify-then-cache"
  },
  "https://cdn.jsdelivr.net/npm/outetts@0.2.0/+esm": {
    "sha256": "3527316a28c71a577923a8f683aae68f2ec7ed0520bb64d5bbee806b51e60279",
    "bytes": 106273,
    "policy": "verify-then-cache"
  }
};
// <<< runtime-integrity

// Third-party runtime integrity. lib/webai.js loads the runtime with a dynamic import(), which has no
// integrity option in browsers today, so the worker is the only place its bytes can be checked.
// Verification runs on EVERY serve - a cache hit as well as a network response - because checking only
// before storing cannot detect an entry poisoned after it was stored.
//
// What this does NOT cover, stated here so it is not mistaken for complete protection: a first
// uncontrolled dynamic import that happens before this worker is controlling, and any browser
// HTTP-cache poisoning, which happens below the worker entirely.
async function sha256Hex(bytes) {
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

// A response whose bytes do not match the pin is never served, from cache or network.
function integrityFailure() {
  return new Response("Runtime integrity check failed", {
    status: 502,
    headers: { "content-type": "text/plain; charset=utf-8" },
  });
}

// The manifest is keyed by URL without query or fragment. jsDelivr version paths are immutable, so a
// query string changes nothing about the bytes and must NOT be a way to slip past verification: an
// exact-match lookup would have treated "...@3.7.5?t=1" as an unknown URL and served it unverified.
function runtimeIntegrityKey(url) {
  const parsed = new URL(url);
  return `${parsed.origin}${parsed.pathname}`;
}

async function verifiedLibraryResponse(req, sha256) {
  // Both the read and the eviction are scoped to the cache this worker owns. caches.match() searches
  // EVERY cache in the origin, so a matching entry in a cache we do not own would be re-read on every
  // request, evict nothing, and force a network fetch each time - an unrecoverable 502 while offline.
  const shell = await caches.open(SHELL_CACHE);
  const cached = await shell.match(req);
  if (cached) {
    if (await sha256Hex(await cached.clone().arrayBuffer()) === sha256) return cached;
    // Poisoned after it was stored. Evict it BEFORE refetching, and await it: a delete left in flight
    // can land after the clean copy is stored and wipe the good entry instead of the bad one.
    await shell.delete(req).catch(() => {});
  }
  let res;
  try {
    res = await fetch(req);
  } catch {
    // Offline with no verified copy available. Fail closed: an unverified runtime is not served.
    return integrityFailure();
  }
  if (!res.ok) return res;
  if (await sha256Hex(await res.clone().arrayBuffer()) !== sha256) return integrityFailure();
  const copy = res.clone();
  shell.put(req, copy).catch(() => {});
  return res;
}

self.addEventListener("install", (e) => {
  self.skipWaiting();
  e.waitUntil(caches.open(SHELL_CACHE).catch(() => {}));
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          // Delete ONLY our own outdated shell caches. transformers-cache and any library cache are
          // load-bearing model storage — never touch them.
          keys.filter((k) => k.startsWith("webai-shell-") && k !== SHELL_CACHE).map((k) => caches.delete(k)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);

  // Model blobs (HF): cache-first across ALL caches, never double-store. transformers.js owns those
  // bytes in its own cache, and re-storing ~GB models is what pushes an origin into quota eviction.
  if (MODEL_HOSTS.includes(url.hostname)) {
    e.respondWith(caches.match(req).then((hit) => hit || fetch(req)));
    return;
  }

  // Third-party runtime JS/WASM (jsDelivr): served only when its bytes match the pinned hash, cache
  // hit or network. A runtime URL that is NOT in the manifest is unknown/unpinned: it is fetched but
  // never served from the shell cache and never stored as a trusted shell asset, so an unlisted
  // runtime cannot inherit trust it was never granted.
  if (LIB_HOSTS.includes(url.hostname)) {
    // `.sha256` and not the entry itself: the manifest maps a URL to { sha256, bytes }, and comparing
    // the hex string against that object is always false, which served 502 for every pinned runtime
    // and broke all Transformers.js routes. The tests missed it because they substituted a manifest of
    // plain strings; they now use the production shape, and a schema test pins it.
    const entry = RUNTIME_INTEGRITY[runtimeIntegrityKey(req.url)];
    if (!entry) {
      e.respondWith(fetch(req));
      return;
    }
    e.respondWith(verifiedLibraryResponse(req, entry.sha256));
    return;
  }

  // Same-origin app shell: cache-first with background revalidation (stale-while-revalidate).
  // Returning users get an instant load from cache — the model check starts immediately instead of
  // after the full HTML/CSS/JS network round-trip — while the network refreshes the cache in the
  // background so the next visit is current. (Previously network-first: every page load serialised
  // the shell round-trip before the demo's "Checking for a local copy…" could even begin, which is
  // what felt like waiting on a server response for an already-local model.)
  if (url.origin === self.location.origin) {
    e.respondWith(
      (async () => {
        const cached = await caches.match(req);
        const network = fetch(req)
          .then((res) => {
            if (res.ok) {
              const copy = res.clone();
              caches.open(SHELL_CACHE).then((c) => c.put(req, copy)).catch(() => {});
            }
            return res;
          })
          .catch(() => cached);
        return cached || network;
      })(),
    );
    return;
  }
});
